:toc:
:toclevels: 5
:toc-title: 目录
:imagesdir: ./images

== Linux

https://jaywcjlove.gitee.io/linux-command[命令手册]

=== Ubuntu

==== 常见问题

link:./pages/install-vmwaretools-on-ubuntu.adoc[Ubuntu安装VMwareTools]

== Nginx

=== 应用实例

link:./pages/build-live-service-with-nginx.adoc[搭建直播服务]

== Git

=== 入门

link:./pages/upload-local-code-to-github.adoc[上传本地代码至Github]

=== 常见问题

link:./pages/can-not-push-local-repo-to-remote-repo.adoc[无法推送本地仓库到远程仓库（新创建并含有默认的README）]

link:./pages/update-fork-repository-on-github.adoc[在Github上更新Fork仓库]

git拉取代码报错：error:RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
解决办法：博客地址：https://blog.csdn.net/qq_37161280/article/details/98758760

克隆报错：error: RPC failed; curl 18 transfer closed with outstanding read data remaining fatal: the remote en
解决办法：https://blog.csdn.net/qq_37161280/article/details/98757267


== Node.js

=== 更换npm下载源

`npm install` 时巨慢无比，这时可以把下载源换成淘宝的。

[source,bash]
----
npm config set registry https://registry.npm.taobao.org
----

淘宝NPM源官网 -  https://npm.taobao.org

=== 框架

==== Thinkjs

*数据库安全*

为了防止数据库密码暴露在公开场合，可以将密码设置为环境变量，然后在 `adapter.js` 中使用 `process.env['variable_name']` 调用系统环境变量。

*踩坑*

* 返回数据库数据时，切记使用 `await` 将异步数据库操作改成同步操作，否则无法获取预期的返回值。

[source, js]
----
findAction() {
  let user = this.model().where({ id: id }).find()
  this.json(user)
}
// response => {}

async findAction() {
  let user = await this.model().where({ id: id }).find()
  this.json(user)
}
// response => { user: { ... } }
----

* 更新 `json` 字段的值时，应当传入字符串形式的值。

[source, js]
----
// wrong
model.where( { id： 1 } ).update('{ key: value }')

// true
model.where( { id： 1 } ).update({ key: value })
----

===== 代码示例

link:./example/file.js[文件上传与下载]

== 微信小程序

=== UI组件库

. https://github.com/Tencent/weui-wxss[weui]
. https://github.com/youzan/vant[vant]

=== 基础

link:./pages/communication-between-miniprogram-and-thinkjs.adoc[Thinkjs与小程序的通信]

=== 实例

link:./pages/use-vant.adoc[使用Vant]


https://juejin.im/entry/5af1b16d6fb9a07aca7a20d3[小程序商城Demo（Thinkjs + MySQL）]

== 数据库

=== MySQL

安装

link:./pages/install-mysql57-on-windows-with-zip-package.adoc[在Windows下安装MySQL(zip格式安装包)]

常见问题

link:./pages/ways-to-resolve-encoding-error-in-mysql.adoc[解决MySQL中编码错误的方法]

其它

[source, mysql]
----
create table user (name varchar(20)) default charset=utf8;
----

link:./pages/quick-refrence-of-mysql-command.adoc[MySQL常见命令快速参考]

=== MongoDB

MongoDB在centos上的安装：

===== 官网的安装教程：https://docs.mongodb.com/manual/tutorial/install-mongodb-on-amazon/

===== 自己百度然后摸索的教程：

1.进入到 /usr/local目录：

`cd  /usr/local`

2.安装必要的插件

`[root@iZuf local]# cd /usr/local`

`[root@iZu local]# yum -y install gcc make gcc-c++ openssl-devel wget`

`[root@iZuf local]# yum install net-tools`

3.下载与 CentOS 系统匹配的mongodb-linux-x86_64-rhel70-3.2.4.tgz 文件 下载很慢

wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-3.2.4.tgz

4.解压缩 mongodb-linux-x86_64-rhel70-3.2.4.tgz 文件：

`tar -zxvf mongodb-linux-x86_64-rhel70-3.2.4.tgz`

5. 重命名 mongodb-linux-x86_64-rhel70-3.2.4 文件为 mongodb3.2.4：

`mv mongodb-linux-x86_64-rhel70-3.2.4 mongodb3.2.4`

6.创建 mongodb 目录

`mkdir -p mongodb`

7.将 mongodb3.2.4 文件从 /usr/local 目录中移动到 /usr/local/mongodb 目录中：

`[root@iZufZ local]# mv mongodb3.2.4 mongodb``

8.进入到 /usr/local/mongodb/mongodb3.2.4 目录中：

`cd mongodb/mongodb3.2.4`

9.在 /usr/local/mongodb/mongodb3.2.4/bin/ 目录中创建一个存放日志的目录：

`mkdir -p data/test/logs`

10. 在 /usr/local/mongodb/mongodb3.2.4/bin/ 目录中创建一个存放数据文件的目录：

`mkdir -p data/test/db`

11.进入 bin 目录中：

`[root@iZuf65sjh5jkbz8k7n6iz2Z mongodb3.2.4]# cd bin`

12. 创建配置文件 mongodb.conf：

`vim mongodb.conf`

13.在 mongodb.conf 写入如下内容：
----
# idae - MongoDB config start - 2016-05-02

# 设置数据文件的存放目录
dbpath = /usr/local/mongodb/mongodb3.2.4/bin/data/test/db

# 设置日志文件的存放目录及其日志文件名
logpath = /usr/local/mongodb/mongodb3.2.4/bin/data/test/logs/mongodb.log

# 设置端口号（默认的端口号是 27017）
port = 27017

# 设置为以守护进程的方式运行，即在后台运行
fork = true

# nohttpinterface = true
nohttpinterface = true
# idae - MongoDB config end - 2016-05-02
先按 ESC ，然后按英文状态下的“:wq”保存并退出；
参数解释：
--dbpath 数据库路径(数据文件)
--logpath 日志文件路径
--master 指定为主机器
--slave 指定为从机器
--source 指定主机器的IP地址
--pologSize 指定日志文件大小不超过64M.因为resync是非常操作量大且耗时，最好通过设置一个足够大的oplogSize来避免resync(默认的 oplog大小是空闲磁盘大小的5%)。
--logappend 日志文件末尾添加，即使用追加的方式写日志
--journal 启用日志
--port 启用端口号
--fork 在后台运行
--only 指定只复制哪一个数据库
--slavedelay 指从复制检测的时间间隔
--auth 是否需要验证权限登录(用户名和密码)
--syncdelay 数据写入硬盘的时间（秒），0是不等待，直接写入
--notablescan 不允许表扫描
--maxConns 最大的并发连接数，默认2000
--pidfilepath 指定进程文件，不指定则不产生进程文件
--bind_ip 绑定IP，绑定后只能绑定的IP访问服务
----
启动MongoDB：

[root@iZuf65sjh5jkbz8k7n6iz2Z bin]# sudo /bin/mongo

重新启动MongoDB数据：

[root@iZuf65sjh5jkbz8k7n6iz2Z bin]# sudo service mongod start



== Web开发

推荐网站：

https://developer.mozilla.org/zh-CN[Mozillia Developer Network]

=== CSS

==== 框架列表

. BootStrap
. Bulma
. Spectre

=== JavaScript

==== 框架列表

. Vue.js

link:./pages/be-careful-when-using-strict-operator.adoc[使用严格运算符时请小心]

[TIP]
====
键值的名称一致时，可简写。

[source, js]
----
let userID = 1
let data1 = { userID: userID }    // { userID: 1 }
let data2 = { userID }    // 简写形式，效果与上面相同
----

反引号（`）中可引用变量。

[source, js]
----
let str1 = 'world'
let str2 = 'hello ' + `${str1}`    // result: 'hello world'
----

====

=== HTTP请求调试工具

客户端软件：Postman

浏览器插件：RESTED（支持Chrome，Firefox）


== Python

*工欲善其事，必先利其器，* https://www.cnblogs.com/liangmingshen/p/9297381.html[PyCharm快捷键大全]

link:./pages/python-basic-knowledge.adoc[1.Python入门了解]

link:./pages/list-and-tuple-Detailed-use-cases.adoc[2.Python基础]

link:./pages/python_object_oriented.adoc[3.Python面向对象]

== Java

=== Spring Boot

==== 创建第一个 Spring Boot 应用

[NOTE]
====
请确保你的电脑安装了 JDK
====

这里我们使用 Gradle 搭配 IntelliJ IDEA 来构建应用。

1. Create New Project，应用类型中选择 Spring Initializer
2. Project 信息填写界面中，Type 选择 Gradle Project
3. Dependencies 中选择 Web ，右侧依赖列表中 选择 Spring Web Starter

然后 IntelliJ IDEA 会提示设置从 Gradle 导入模块的配置。

只需要开启自动导入和勾选使用本地 Gradle 即可。

项目创建完毕后，IntelliJ IDEA 会开始自动下载相关文件，但是 maven repo 在国内访问过慢，我们需要将它更换为国内阿里 maven repo 地址。

.build.gradle
....
repositories {
    maven {
        url "https://maven.aliyun.com/repository/central"
    }
    mavenLocal()
    mavenCentral()
}
....

然后在右侧边栏中打开 Gradle 管理面板，在项目名上右键，选择刷新 Gradle 项目即可。

== 美化

Windows 下 CMD 和 PowerShell 推荐使用 http://www.downcc.com/font/17200.html[Microsoft Yahei Mono] 字体。

Git bash 可以使用 https://github.com/tonsky/FiraCode/releases[Fira Code] 字体。

VS Code 下推荐 Material Theme，Atom One Dark 之类的主题。

== 提升自我修养

https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways[《别像弱智一样提问》]

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md[《提问的智慧》]

https://www.zhihu.com/question/60809486[《有哪些看似很傻，实则很聪明的行为？》]
