:toc:

== Git

=== 上传本地代码至Github

为什么要传到 Github 中呢，因为，你用过就会知道有多么美妙了！（By: 陈鑫）

1. 在 Github 中创建一个和自己项目名字一样的仓库
  eg: 我自己创建的就是一个文件夹 demo
2. 打开 Git bash
  在自己本地的项目 demo 文件夹中，在空白处，使用鼠标右键选择 `Git bash here`
3. 初始化 Git 仓库
  git init 
4. 添加远程仓库地址
  git remote add origin https://github.com/WhiteLie1/demo.git    // 请使用你自己的仓库地址
5. 添加文件至暂存区
  git add -A    // 添加所有文件
6. 提交暂存区的修改（提交至本地）
  git commit -m "Init repo"
7. 将代码推送到远程仓库的 master （主）分支
  git push -u origin master

当远程数据仓库和本体的关联以后就可以进行日常的操作了。

首先呢，一定是在你项目当前的目录下打开 `Git bash here` ,然后你需要做的是：

[source, bash]
----
// 添加所有修改过或新增的文件
git add . 

// 查看文件状态
git status

// 提交并说明修改情况
git commit -m "修改了某文件"

/ 推送到远程仓库
git push

== Node.js

=== 更换npm下载源

`npm install` 时巨慢无比，这时可以把下载源换成淘宝的。

[source,bash]
----
npm config set registry https://registry.npm.taobao.org
----

淘宝NPM源官网 -  https://npm.taobao.org

=== Think.js框架

*热更新*

`Think.js` 框架支持热更新操作，保存文件后会自动重新部署，即刻生效，你可以在终端输出中看到相关信息。

而在 `java` 中，针对 `controller` 也就是 `servlet` 的修改操作，需要 `Redelploy` 或者 `Restart` 来使得更改生效，整个过程耗时要长一些。

*数据库安全*

为了防止数据库密码暴露在公开场合，可以将密码设置为环境变量，然后在 `adapter.js` 中使用 `process.env['variable_name']` 调用系统环境变量。

*踩坑*

* 返回数据库数据时，切记使用 `await` 将异步数据库操作改成同步操作，否则无法获取预期的返回值。

[source, js]
----
findAction() {
  let user = this.model().where({ id: id }).find()
  this.json(user)
}
// response => {}

async findAction() {
  let user = await this.model().where({ id: id }).find()
  this.json(user)
}
// response => { user: { ... } }
----

* 更新 `json` 字段的值时，应当传入字符串形式的值。

[source, js]
----
// wrong
model.where( { id： 1 } ).update('{ key: value }')

// true
model.where( { id： 1 } ).update({ key: value })
----

简单下载功能

[source, js]
----
const chars = '0123456789abcdefghijklmnopqrstuvwxyz!@#$%^&*()_+-=<>/?[]{}'
const reverseChars = Array.from(chars).reverse().toString()

module.exports = class extends think.Controller {
  // 上传文件成功后，返回仅供外部查看的虚拟文件名
  async uploadAction () {
    let file = this.file('file')
    let filepath = think.ROOT_PATH + '/www/static/upload/' + file.name
    think.mkdir(path.dirname(filepath))
    await rename(file.path, filepath)
    this.body = encrypt(file.name)    // 返回加密的文件名
  }
  async downloadAction () {
    // 获取真实文件名后，再跳转下载
    let filename = decrypt(this.ctx.param('f'))
    this.ctx.download(think.ROOT_PATH + '/www/static/upload/' + filename)
  }
}

function encrypt (filename)  {
  return convert(filename, chars, reverseChars)
}

function decrypt (filename) {
  return convert(filename, reverseChars, chars)
}

/*
 * 简单的字符串转换
 * 将输入串中的每一个 char 从 currentChars 转换成 targetChars 中对应的 char
 */
function convert(str, currentChars, targetChars) {
  let len = str.length
  let ret = ''
  for (let i = 0; i < len; ++i) {
    let ch = str.charAt(i)
    let index = currentChars.indexOf(ch)
    if (index != -1) {
      ch = targetChars.charAt(index)
    }
    ret += ch
  }
  return ret
}
----

== 数据库

=== MySQL

==== 安装

以Windows下zip格式的文件（版本5.7）安装为例：

1. 打开powershell（管理员模式）

  使用快捷键 WIN + X => A

2. 进入mysql目录
  
  cd 'mysql_dir/bin'

3. 执行初始化操作

  ./mysqld --initialize

4. 查看初始化生成的默认密码

  在搜索栏中输入 *.err，密码就在这个文件中（一般是最后一行，比如：'A temporary password......'）

5. 启动mysql

  ./mysqld --console

6. 添加环境变量（方便使用mysql相关命令）

  在path变量中新增'/mysql_dir/bin'

7. 登陆

  mysql -uroot -p

8. 更改密码

  alter user 'root'@localhost identified by 'new password'

9. 中文乱码
  
  * sqlyog 中取消勾选表属性中隐藏语言选项（最右）
  
      选择字符集为utf8,核对为utf8_general_ci

  * 查看数据库编码

      show variables like "%char%"

  * 设置character_set_client,character_set_connection,character_set_results的方法
     
      set names utf8

  * 设置character_set_database,character_set_server为utf8的方法

      找到数据库安装目录下my.ini文件

      [mysqld]下增加character-set-server=utf8

      [client]下增default-character-set=utf8

      [mysql]下增default-character-set=utf8

  * 重启服务
      
      net stop mysql

      net start mysql


官方文档 - https://dev.mysql.com/doc/refman/5.7/en/windows-install-archive.html

==== 命令快速参考
创建表

----
// 一般形式
CREATE TABLE table_name (id int primary key auto_increment ... )

// 含外键
CREATE TABLE order (
  id int primary key auto_increment,
  user_id int,
  vendor_id int
  foreign key (user_id) references user(id),
  foreign key (vendor_id) references vendor(id)
)
----

更新字段

  UPDATE user SET name = 'Jack' WHERE id = 1;

删除记录

  DELETE FROM user where id = 1;

删除表

  DROP TABLE user;

更改字段定义

  ALTER TABLE user MODIFY nickname varchar(100) default 'newUser'; 



== Web开发

推荐网站：

https://developer.mozilla.org/zh-CN[Mozillia Developer Network]

=== JavaScript

当键值的名称一致时，可采用简写形式。

[source, js]
----
let userID = 1
let data1 = { userID: userID }    // { userID: 1 }
let data2 = { userID }    // 简写形式，效果与上面相同
----

在反引号（`）中引用变量

[source, js]
----
let str1 = 'world'
let str2 = 'hello ' + `${str1}`    // result: 'hello world'
----

运算符

`===` 表示等于
`!==` 表示不等于

=== HTTP请求调试工具

客户端软件：Postman

浏览器插件：RESTED（支持Chrome，Firefox）

== 美化

Windows 下 CMD 和 PowerShell 推荐使用 http://www.downcc.com/font/17200.html[Microsoft Yahei Mono] 字体。

Git bash 可以使用 https://github.com/tonsky/FiraCode/releases[Fira Code] 字体。

VS Code 下推荐 Material Theme，Atom One Dark 之类的主题。

== 提升自我修养

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md[《提问的智慧》]