:toc:
== Git

== Node.js

=== 更换npm下载源

`npm install` 时巨慢无比，这时可以把下载源换成淘宝的。

[source,bash]
----
npm config set registry https://registry.npm.taobao.org
----

淘宝NPM源官网 -  https://npm.taobao.org

=== Think.js框架

*热更新*

`Think.js` 框架支持热更新操作，保存文件后会自动重新部署，即刻生效，你可以在终端输出中看到相关信息。

而在 `java` 中，针对 `controller` 也就是 `servlet` 的修改操作，需要 `Redelploy` 或者 `Restart` 来使得更改生效，整个过程耗时要长一些。

*数据库安全*

为了防止数据库密码暴露在公开场合，可以将密码设置为环境变量，然后在 `adapter.js` 中使用 `process.env['variable_name']` 调用系统环境变量。

*踩坑*

* 返回数据库数据时，切记使用 `await` 将异步数据库操作改成同步操作，否则无法获取预期的返回值。

[source, js]
----
findAction() {
  let user = this.model().where({ id: id }).find()
  this.json(user)
}
// response => {}

async findAction() {
  let user = await this.model().where({ id: id }).find()
  this.json(user)
}
// response => { user: { ... } }
----

* 更新 `json` 字段的值时，应当传入字符串形式的值。

[source, js]
----
// wrong
model.where( { id： 1 } ).update('{ key: value }')

// true
model.where( { id： 1 } ).update({ key: value })
----

== 数据库

=== MySQL安装

以Windows下zip格式的文件（版本5.7）安装为例：

1. 打开powershell（管理员模式）

  使用快捷键 WIN + X => A

2. 进入mysql目录
  
  cd 'mysql_dir/bin'

3. 执行初始化操作

  ./mysqld --initialize

4. 查看初始化生成的默认密码

  在搜索栏中输入 *.err，密码就在这个文件中（一般是最后一行，比如：'A temporary password......'）

5. 启动mysql

  ./mysqld --console

6. 添加环境变量（方便使用mysql相关命令）

  在path变量中新增'/mysql_dir/bin'

7. 登陆

  mysql -uroot -p

8. 更改密码

  alter user 'root'@localhost identified by 'new password'

官方文档 - https://dev.mysql.com/doc/refman/5.7/en/windows-install-archive.html

== Web开发

=== JavaScript

当键值的名称一致时，可采用简写形式。

[source, js]
----
let userID = 1
let data1 = { userID: userID }    // { userID: 1 }
let data2 = { userID }    // 简写形式，效果与上面相同
----

=== HTTP请求调试工具

客户端软件：Postman

浏览器插件：RESTED（支持Chrome，Firefox）

陈鑫7月16日笔记
vscode中如何把代码上传到github中
（为什么要传到github中呢，因为，你用过就会知道有多么美妙了！）
第一步：
先在github中创建一个和自己项目名一样的仓库名字
比如：我自己创建的就是一个文件 demo
第二步：
在自己本地的项目 demo 文件夹中打开 git bush  here
然后重要的操作来了：
1.git init 这个很重要，初始化一个仓库或者新建一个仓库
$ git init
2.初始化一个仓库 这个在新建的github项目中都有，在最下面
$ git remote add origin https://github.com/WhiteLie1/demo.git
(注意这个网址一样的东西，在你新创建的那个仓库界面最下面里面都有)
3.add -A 添加所有文件
$ git add -A
4.上传说明这是一个初始化操作
$ git commit -m "init"
5.上传到一个原始仓库的主分支上面
$ git push -u origin master

当远程数据仓库和本体的关联以后就可以进行日常的操作了
首先呢，一定是在你项目当前的目录下打开git bush here 要做的是：
Git add . 添加所有文件
查看状态
Git status
提交说明：
Git commit -m "此次提交说明文档"
推送到远程仓库
Git push

文件的传输
const fs = require('fs');
const path = require('path');
const rename = think.promisify(fs.rename, fs); // 通过 promisify 方法把 rename 方法包装成 Promise 接口
module.exports = class extends think.Controller {
async uploadAction(){
const file = this.file('image');
// 如果上传的是 png 格式的图片文件，则移动到其他目录
if(file ) {//===三个等号是等于 不等于则是 ！==
const filepath = path.join(think.ROOT_PATH, 'runtime/upload/a.png');
think.mkdir(path.dirname(filepath));
await rename(file.path, filepath)
}
}
}

怎么实现 在upload中实现download逻辑 下载好这个东西





更改路径









