:toc:
:imagesdir: ./images

== Linux

https://jaywcjlove.gitee.io/linux-command[命令手册]

=== Ubuntu

==== 常见问题

link:./pages/install-vmwaretools-on-ubuntu.adoc[Ubuntu安装VMwareTools]

== Nginx

=== 应用实例

link:./pages/build-live-service-with-nginx.adoc[搭建直播服务]

== Git

=== 入门

link:./pages/upload-local-code-to-github.adoc[上传本地代码至Github]

=== 常见问题

link:./pages/can-not-push-local-repo-to-remote-repo.adoc[无法推送本地仓库到远程仓库（新创建并含有默认的README）]

link:./pages/update-fork-repository-on-github.adoc[在Github上更新Fork仓库]

git拉取代码报错：error:RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
解决办法：博客地址：https://blog.csdn.net/qq_37161280/article/details/98758760

克隆报错：error: RPC failed; curl 18 transfer closed with outstanding read data remaining fatal: the remote en
解决办法：https://blog.csdn.net/qq_37161280/article/details/98757267


== Node.js

=== 更换npm下载源

`npm install` 时巨慢无比，这时可以把下载源换成淘宝的。

[source,bash]
----
npm config set registry https://registry.npm.taobao.org
----

淘宝NPM源官网 -  https://npm.taobao.org

=== 框架

==== Thinkjs

*数据库安全*

为了防止数据库密码暴露在公开场合，可以将密码设置为环境变量，然后在 `adapter.js` 中使用 `process.env['variable_name']` 调用系统环境变量。

*踩坑*

* 返回数据库数据时，切记使用 `await` 将异步数据库操作改成同步操作，否则无法获取预期的返回值。

[source, js]
----
findAction() {
  let user = this.model().where({ id: id }).find()
  this.json(user)
}
// response => {}

async findAction() {
  let user = await this.model().where({ id: id }).find()
  this.json(user)
}
// response => { user: { ... } }
----

* 更新 `json` 字段的值时，应当传入字符串形式的值。

[source, js]
----
// wrong
model.where( { id： 1 } ).update('{ key: value }')

// true
model.where( { id： 1 } ).update({ key: value })
----

===== 代码示例

link:./example/file.js[文件上传与下载]

== 微信小程序

=== UI组件库

. https://github.com/Tencent/weui-wxss[weui]
. https://github.com/youzan/vant[vant]

=== 基础

link:./pages/communication-between-miniprogram-and-thinkjs.adoc[Thinkjs与小程序的通信]

=== 实例

https://juejin.im/entry/5af1b16d6fb9a07aca7a20d3[小程序商城Demo（Thinkjs + MySQL）]

== 数据库

=== MySQL

安装

link:./pages/install-mysql57-on-windows-with-zip-package.adoc[在Windows下安装MySQL(zip格式安装包)]

常见问题

link:./pages/ways-to-resolve-encoding-error-in-mysql.adoc[解决MySQL中编码错误的方法]

其它

[source, mysql]
----
create table user (name varchar(20)) default charset=utf8;
----

link:./pages/quick-refrence-of-mysql-command.adoc[MySQL常见命令快速参考]

=== MongoDB

待补充

== Web开发

推荐网站：

https://developer.mozilla.org/zh-CN[Mozillia Developer Network]

=== CSS

==== 框架列表

. BootStrap
. Bulma
. Spectre

=== JavaScript

==== 框架列表

. Vue.js

link:./pages/be-careful-when-using-strict-operator.adoc[使用严格运算符时请小心]

[TIP]
====
键值的名称一致时，可简写。

[source, js]
----
let userID = 1
let data1 = { userID: userID }    // { userID: 1 }
let data2 = { userID }    // 简写形式，效果与上面相同
----

反引号（`）中可引用变量。

[source, js]
----
let str1 = 'world'
let str2 = 'hello ' + `${str1}`    // result: 'hello world'
----

====

=== HTTP请求调试工具

客户端软件：Postman

浏览器插件：RESTED（支持Chrome，Firefox）


== Python

link:./pages/python-basic-knowledge.adoc[1.Python入门了解]

link:./pages/list-and-tuple-Detailed-use-cases.adoc[2.Python基础]

== Java

=== Spring Boot

==== 创建第一个 Spring Boot 应用

[NOTE]
====
请确保你的电脑安装了 JDK
====

这里我们使用 Gradle 搭配 IntelliJ IDEA 来构建应用。

1. Create New Project，应用类型中选择 Spring Initializer
2. Project 信息填写界面中，Type 选择 Gradle Project
3. Dependencies 中选择 Web ，右侧依赖列表中 选择 Spring Web Starter

然后 IntelliJ IDEA 会提示设置从 Gradle 导入模块的配置。

只需要开启自动导入和勾选使用本地 Gradle 即可。

项目创建完毕后，IntelliJ IDEA 会开始自动下载相关文件，但是 maven repo 在国内访问过慢，我们需要将它更换为国内阿里 maven repo 地址。

.build.gradle
....
repositories {
    maven {
        url "https://maven.aliyun.com/repository/central"
    }
    mavenLocal()
    mavenCentral()
}
....

然后在右侧边栏中打开 Gradle 管理面板，在项目名上右键，选择刷新 Gradle 项目即可。

== 美化

Windows 下 CMD 和 PowerShell 推荐使用 http://www.downcc.com/font/17200.html[Microsoft Yahei Mono] 字体。

Git bash 可以使用 https://github.com/tonsky/FiraCode/releases[Fira Code] 字体。

VS Code 下推荐 Material Theme，Atom One Dark 之类的主题。

== 提升自我修养

https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways[《别像弱智一样提问》]

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md[《提问的智慧》]

https://www.zhihu.com/question/60809486[《有哪些看似很傻，实则很聪明的行为？》]
