:toc:
:imagesdir: ./images

== Linux

https://jaywcjlove.gitee.io/linux-command[命令手册]


=== Ubuntu

==== 常见问题

link:.pages/install-vmwaretools-on-ubuntu.adoc[Ubuntu安装VMwareTools]

== Nginx

=== 应用实例

link:./pages/build-live-service-with-nginx.adoc[搭建直播服务]

== Git

=== 入门

link:.pages/upload-local-code-to-github.adoc[上传本地代码至Github]

=== 常见问题

link:./pages/can-not-push-local-repo-to-remote-repo.adoc[无法推送本地仓库到远程仓库（新创建并含有默认的README）]

link:./pages/update-fork-repository-on-github.adoc[在Github上更新Fork仓库]


== Node.js

=== 更换npm下载源

`npm install` 时巨慢无比，这时可以把下载源换成淘宝的。

[source,bash]
----
npm config set registry https://registry.npm.taobao.org
----

淘宝NPM源官网 -  https://npm.taobao.org

=== 框架

==== Thinkjs

*数据库安全*

为了防止数据库密码暴露在公开场合，可以将密码设置为环境变量，然后在 `adapter.js` 中使用 `process.env['variable_name']` 调用系统环境变量。

*踩坑*

* 返回数据库数据时，切记使用 `await` 将异步数据库操作改成同步操作，否则无法获取预期的返回值。

[source, js]
----
findAction() {
  let user = this.model().where({ id: id }).find()
  this.json(user)
}
// response => {}

async findAction() {
  let user = await this.model().where({ id: id }).find()
  this.json(user)
}
// response => { user: { ... } }
----

* 更新 `json` 字段的值时，应当传入字符串形式的值。

[source, js]
----
// wrong
model.where( { id： 1 } ).update('{ key: value }')

// true
model.where( { id： 1 } ).update({ key: value })
----

===== 代码示例

link:./example/file.js[文件上传与下载]

== 微信小程序

=== UI组件库

. https://github.com/Tencent/weui-wxss[weui]
. https://github.com/youzan/vant[vant]

=== 基础

link:./pages/communication-between-miniprogram-and-thinkjs.adoc[Thinkjs与小程序的通信]

=== 实例

https://juejin.im/entry/5af1b16d6fb9a07aca7a20d3[小程序商城Demo（Thinkjs + MySQL）]

== 数据库

=== MySQL

安装

link:.pages/install-mysql57-on-windows-with-zip-package.adoc[在Windows下安装MySQL(zip格式安装包)]

常见问题

link:.pages/ways-to-resolve-encoding-error-in-mysql.adoc[解决MySQL中编码错误的方法]

其它

[source, mysql]
----
create table user (name varchar(20)) default charset=utf8;
----

link:.pages/quick-refrence-of-mysql-command.adoc[MySQL常见命令快速参考]

=== MongoDB

待补充

== Web开发

推荐网站：

https://developer.mozilla.org/zh-CN[Mozillia Developer Network]

=== CSS

==== 框架列表

. BootStrap
. Bulma
. Spectre

=== JavaScript

==== 框架列表

. Vue.js

link:.pages/be-careful-when-using-strict-operator.adoc[使用严格运算符时请小心]

[TIP]
====
键值的名称一致时，可简写。

[source, js]
----
let userID = 1
let data1 = { userID: userID }    // { userID: 1 }
let data2 = { userID }    // 简写形式，效果与上面相同
----

反引号（`）中可引用变量。

[source, js]
----
let str1 = 'world'
let str2 = 'hello ' + `${str1}`    // result: 'hello world'
----

====

=== HTTP请求调试工具

客户端软件：Postman

浏览器插件：RESTED（支持Chrome，Firefox）


== Python

=== 语言类型

编译型语言（如：C）执行步骤：
翻译 => 全部翻译完毕 => 执行

解释型语言（如：Python）执行步骤：
翻译 => 执行 => 翻译 => 执行

比较：

速度：编译型语言比解释型语言执行速度快

跨平台：解释型语言比编译型语言跨平台性好

=== 常见错误

====== 手误敲错单词或者定义的变量，仔细查看控制台输出！

====== 多条语句写在同一行

例如：`print("Hello")print("World")`

 `SyntaxError: invalid syntax`
*语法错误：语法无效*

每行代码负责完成一个动作

==== 缩进错误
 `IndentationError: unexpected indent`
*缩进错误*：不期望出现的缩进

Python语言格式很严格，每行代码要对齐

==== 关于中文

Python2解释器编译中文会报错,
但是Python3解释器可以编译中文

用法  `Python3 文件名.py`
    
==== 交互式运行Python程序

*方法*：在终端中键入python或python3进入python解释器，输入exit()或使用快捷键ctrl+D退出官方解释器。

*优点*：适用于学习/验证Python语法或局部代码。
*缺点*：代码无法保存，不适合运行太大的程序。

==== if判断语句

----
if 判断条件1:
    执行语句1……
elif 判断条件2:
    执行语句2……
elif 判断条件3:
    执行语句3……
else:
    执行语句4……
----

这里需要注意的是，`else` 后面不能跟条件判断语句，不然会报错 `SyntaxError: invalid syntax`

*语法错误：非法语法*

link:./pages/list-and-tuple-Detailed-use-cases.adoc[1.list和tuple详细用例]

== 美化

Windows 下 CMD 和 PowerShell 推荐使用 http://www.downcc.com/font/17200.html[Microsoft Yahei Mono] 字体。

Git bash 可以使用 https://github.com/tonsky/FiraCode/releases[Fira Code] 字体。

VS Code 下推荐 Material Theme，Atom One Dark 之类的主题。

== 提升自我修养

https://github.com/tangx/Stop-Ask-Questions-The-Stupid-Ways[《别像弱智一样提问》]

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md[《提问的智慧》]

https://www.zhihu.com/question/60809486[《有哪些看似很傻，实则很聪明的行为？》]
