*问题背景：*

新建远程仓库时，初始化了 `README.md` 。

在本地项目文件下，使用 `git init` 初始化了仓库，准备推送到远程仓库，但是会提示错误，比如：`Updates were rejected because the remote contains work that you do
hint: not have locally` 。

[source, bash]
----
$ git push --set-upstream origin master

To gitee.com:xiexingchao/git-command-test.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@gitee.com:xiexingchao/git-command-test.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
----

本地与远程分支不一致，其实就是本地少了个 `README.md`，但是又多了一些其它文件。

按照提示，执行 `git pull` 命令，获取远程分支信息。

[source, bash]
----
$ git pull
warning: no common commits
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
From gitee.com:xiexingchao/git-command-test
 * [new branch]      master     -> origin/master
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

git branch --set-upstream-to=origin/<branch> master
----

获取了远程分支信息后，需要对远程的 `master` 和本地的 `master` 分支进行一个合并，以解决它们之间的冲突。

[source, bash]
----
$ git merge origin/master master
fatal: refusing to merge unrelated histories
----

合并时依旧有问题，它提示无法合并不相关的历史。

我们可以在官方文档对 `git merge` 命令的介绍中找到这个选项：

.--allow-unrelated-histories
By default, git merge command refuses to merge histories that do not share a common ancestor. This option can be used to override this safety when merging histories of two projects that started their lives independently. As that is a very rare occasion, no configuration variable to enable this by default exists and will not be added.

`git` 默认不允许合并那些没有公共祖先节点的历史。而我们的远程分支和本地分支都是起点（祖先节点）。所以使用该选项来覆写 `git` 的规则，即破例允许这样合并。

[source, bash]
----
$ git merge origin/master master --allow-unrelated-histories

Merge made by the 'recursive' strategy.
 README.en.md | 36 ++++++++++++++++++++++++++++++++++++
 README.md    | 39 +++++++++++++++++++++++++++++++++++++++
 2 files changed, 75 insertions(+)
 create mode 100644 README.en.md
 create mode 100644 README.md
----

*关于合并冲突问题*

* 问题描述

最近我在拉取git仓库时出现了如下问题

[source, bash]
----
$ git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
----

* 解决方法

首先我先将我github上Fork仓库 `pull request` 更新到最新版本，然后在经过在网上的查找，我使用这种方法一行代码解决了

1.将本地的冲突文件冲掉，不仅需要 `reset` 到 `MERGE-HEAD` 或者 `HEAD` ,还需要 `--hard`。没有后面的 `hard`，不会冲掉本地工作区。只会冲掉 `stage` 区。

只需使用 `git reset --hard FETCH_HEAD`

2.git pull就会成功。
